export const CommanData = [
  {
    id: 1,
    name: "cough & Cold?",
    image: "./assets/img/commanhealth/khok.jpg",
    price: "₹399",
    button: "Consult Now",
  },
  {
    id: 2,
    name: "Period?",
    image: "./assets/img/commanhealth/sto.jpg",
    price: "₹499",
    button: "Consult Now",
  },
  {
    id: 3,
    name: "Sexual issues?",
    image: "./assets/img/commanhealth/cp.jpg",
    price: "₹499",
    button: "Consult Now",
  },
  {
    id: 4,
    name: "Skin problems?",
    image: "./assets/img/commanhealth/hair.jpg",
    price: "₹599",
    button: "Consult Now",
  },
  {
    id: 5,
    name: "Depression?",
    image: "./assets/img/commanhealth/tension.jpg",
    price: "₹499",
    button: "Consult Now",
  },
  {
    id: 6,
    name: "lose weight?",
    image: "./assets/img/commanhealth/child.jpg",
    price: "₹350",
    button: "Consult Now",
  },
  {
    id: 7,
    name: "Stomach issues?",
    image: "./assets/img/commanhealth/stoma.jpg",
    price: "₹399",
    button: "Consult Now",
  },
  {
    id: 8,
    name: "Veginal infection?",
    image: "./assets/img/commanhealth/infection.jpg",
    price: "₹499",
    button: "Consult Now",
  },
  {
    id: 9,
    name: "Sick Kid?",
    image: "./assets/img/commanhealth/sick.jpg",
    price: "₹499",
    button: "Consult Now",
  },
];
